### ISSUE TITLE
Fix content scaling 

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-arkit-unity#10]
For example, the map is currently being scaled according to latitude (which is a hack). This scaling should be done with a more "robust" method. For inspiration/reference: https://forum.unity.com/threads/scaled-content.500620/

**Comment by wilhelmberg** [comment]
> For example, the map is currently being scaled according to latitude (_which is a hack_).

Adding a bit of background information as this is not _a hack_ per se, but common practice in GIS because of the distortions of the WebMercator projection and its inability to be useful for any type of measurement (distance, direction, area).

Unfortunately that implementation doesn't seem to play well with our SDK, Unity or AR.

**_Not tested:_**
**A quick fix/workaround/hack for the SDK might be to always scale as if the current tile (data) were positioned at the equator, passing `0` for latitude.**

-----

[GIS StackExchange: What's the accuracy of Web Mercator EPSG:3857?](https://gis.stackexchange.com/a/184665)

> As a first step, you could look at the distortions of the Mercator projection, which is a conformal projection. **Distance with this projection is only correct along the equator**, then the **error increase with the latitude**. Indeed, as you can see on a global view, the parallels keep the same legnth on the maps. For example, the **horizontal scale factor, which is 1 at the equator**, is equal to **1.15 at a latitude of 30° (_15% error_)**, **2 at a latitude of 60° (_200% error_) and 11.5 at a latitude of 85° (_11,500% error_)** (scale factor 1/cos(latitude) )

----

[Wikipedia: Mercator projection](https://en.wikipedia.org/wiki/Mercator_projection)


[Web Mercator distortion](https://en.wikipedia.org/wiki/Mercator_projection#Distortion) shown via [Tissot's indicatrices](https://en.wikipedia.org/wiki/Tissot%27s_indicatrix):
![image](https://user-images.githubusercontent.com/4549888/32439207-ffc1eaf0-c2ed-11e7-91ef-db60da33f89c.png)

> The Mercator projection portrays Greenland as larger than Australia; in actuality, Australia is more than three and a half times as large as Greenland.

![image](https://user-images.githubusercontent.com/4549888/32439183-d8a81f98-c2ed-11e7-8a4c-a3f7639c228f.png)

----

[Geospatiality: The Web Mercator Visual and Data Analysis Fallacy](https://glenbambrick.com/2016/02/03/web-mercator-fallacy/)

Cylindrical Projection: The Cause for Distortion in a Web Mercator:
![image](https://user-images.githubusercontent.com/4549888/32439484-423ed46e-c2ef-11e7-9dcc-c11f1b568125.png)


----

[ESRI: Why are my map, distance and area measurements wrong when using WGS 1984 Web Mercator?](http://support.esri.com/en/technical-article/000011356)

**Aitoff projection** ("realistic" shape and area, poles are points):
![image](https://user-images.githubusercontent.com/4549888/32438914-a5c275fc-c2ec-11e7-8afe-babf59e8e1d1.png)

**Web Mercator** (extreme distortion, poles cannot even be displayed, _Antarctica appears larger than the land masses of the other six continents combined_):
![image](https://user-images.githubusercontent.com/4549888/32438944-c8ba54e4-c2ec-11e7-84c1-f7d00e400ba9.png)

**Comment by david-rhodes** [comment]
Current map scaling is done with `MapAtWorldScale` component. Note that `RelativeScale` needs to be checked.
