### ISSUE TITLE
AverageHeadingAlignmentStrategy doesn't calculate circular average over 360°

### ISSUE THREAD

**Issue by Crashthatch** [mapbox/mapbox-arkit-unity#18]
Consider 2 alignments: 10° and 350°. The "midpoint" of these alignments should be 0°, but the [current calculation](https://github.com/mapbox/mapbox-arkit-unity/blob/e9b7462908b8fdeb3064e5995aa54cfbaab5d7cd/Assets/Mapbox/Unity/Ar/AverageHeadingAlignmentStrategy.cs#L48) will calculate it as (10+350)/2 = 180°, which isn't really what we want.

Even if the rotations provided were in (-180, 180], the calculation would fail for -10° and 10° ((-10+360) + 10)/2 = (350+10)/2 = 180 as above.

I think this requires [Mean of circular quantities](https://en.wikipedia.org/wiki/Mean_of_circular_quantities) to calculate the "average" heading close to the observations. But I'm confused as to how it seems to work at the moment?

**Comment by david-rhodes** [comment]
🍪 Another one down--good find.

I'll readily admit that this entire class was actually a hack (time may have been a factor). This sort of filtering should actually be done as part of the context (alignment generation), as it would also affect the resultant positions.

In an ideal world, I think the following would work much better:
- Use linear regression on GPS nodes to find line of best fit (or simply filter out impossible location updates based on velocity/acceleration)
- Compute heading from line angle
- Remove nodes which are outliers (using standard deviation)

This wouldn't work well at corners/turns, so we would need an angle threshold for which to restart the whole process.

> I think this requires Mean of circular quantities to calculate the "average" heading close to the observations. But I'm confused as to how it seems to work at the moment?

Sounds good. As to how it works now: the described issue would only happen if you are walking North, and then an alignment simply won't happen because of the angle comparison check. Yes, it's an issue that needs to be fixed, but would rarely occur?

**Comment by Crashthatch** [comment]
>Yes, it's an issue that needs to be fixed, but would rarely occur?

I'm not sure about that... I saw this while walking in a straight line (admittedly I turned around part way through this capture). GPS (compass) heading shows the heading staying at ~140 degrees +/- 20 degrees, but the orange heading is bouncing between -155° and +60°.

I haven't confirmed that it was caused by this bug, but it seems a likely candidate?

![image](https://user-images.githubusercontent.com/186067/32959330-37d07190-cbb9-11e7-8bbf-cd9eb6094642.png)


I agree linear-regression & standard deviation would work to remove spurious GPS readings. 
But is there a better way where the net result of ALL GPS movements is compared to the sum of ALL AR movements since the app started (or tracking was last lost) rather than breaking it up into small sections? That way, turning corners is not such an issue because the "10m north then 1m west" from AR is compared to 2 GPS readings from the start and end of the journey?

**Comment by david-rhodes** [comment]
See https://github.com/mapbox/mapbox-arkit-unity/pull/17#issuecomment-345305846 for reference to the heading values that are bouncing back and forth. I think this was introduced with your PR changes (and that log is sent from the context--not from `AverageHeadingAlignment`).

> But is there a better way where the net result of ALL GPS movements is compared to the sum of ALL AR movements since the app started (or tracking was last lost) rather than breaking it up into small sections? That way, turning corners is not such an issue because the "10m north then 1m west" from AR is compared to 2 GPS readings from the start and end of the journey?

I'm not sure I understand this question. Ideally, all data would be cached and compared to. But, it sounds like you would need some sort of "shape detection" algorithm?
