### ISSUE TITLE
Inaccurate positions when you are far accurate when you are near

### ISSUE THREAD

**Issue by diegoarx** [mapbox/mapbox-arkit-unity#43]
When i put objects in map using SpawnOnMap script they appear not exactly in the location i gave but the more you get near them the more accurate are their positions, why happens this? i notice as i move to the virtual object it corrects its position smoothly, it doesnt jump from one position to other but as you move

**Comment by david-rhodes** [comment]
@diegoarx What you are experiencing is by design. The more data you feed the system (GPS probes/traces), the better the system is at rectifying the AR and GPS positions. Naturally, it is better to observe this over time than as a snap.

The reason results are bad when further away is simple mathematics: https://en.wikipedia.org/wiki/Arc_(geometry)

The length of an arc will grow with its radius (your distance from the object). Therefore, 5 degrees of angle (heading) disparity observed at 50 meters is far more significant than 5 degrees of angle disparity observed at 5 meters.
