### ISSUE TITLE
Zoomable Map in AR

### ISSUE THREAD

**Issue by alt-ctrl-dev** [mapbox/mapbox-arkit-unity#44]
I've been trying to import the Zoomable Map example into the ARTabletopScene, but it does not seem to allow drag like it does in the demo.

Thing that I've attached to the map gameobject:
![image](https://user-images.githubusercontent.com/1557519/36519251-7ffc1610-17de-11e8-9954-25f1f81de53c.png)

Can I please get help to figure out why it doesn't work?

**Comment by alt-ctrl-dev** [comment]
[UPDATE]: My aim is to achieve a mix of the Zoomable Map demo and the interactive POI demo.

**Comment by abhishektrip** [comment]
@reubenkcoutinho This will be available with v1.4.1 release, scheduled for sometime next week.

**Comment by MiroMuse** [comment]
@reubenkcoutinho going to close this ticket for now. Let us know if you need anything else!

**Comment by dhruvmodhapp** [comment]
FOR AR you should use WorldScaleAR example and then try to integrate some of Zoomable map example scripts.
---- You should add 'ReloadMap.cs' and 'QuadTreeCameraMovement.cs' script on ArAlignedMap gameobject. In QuadTreeCameraMovement script's Reference Camera assign as MapCamera.
- this will work well.
- When you go for AR Camera view. You need to disable "QuadTreeCameraMovement" script. Because when you keep enabling this script then it will spoiled your ar-view object position. In Map view, you need to enable QuadTreeCameraMovement script.
- This is working for me greatly. A map is zoom in-out work proper and ar-view also going well.
